source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxOptional Examples' do
  pod 'RxOptional', :path => '../'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift-3.0'
end

target 'RxOptional Tests' do
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'master'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # slience Xcode for asking us migrate to Swift 3
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
